=== iamfreetofly/iamfreetofly.github.io/script.module.turtle/lib/definition/turtle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="https://code.google.com/p/apple-tv2-xbmc/turtle/"
	targetNamespace="https://code.google.com/p/apple-tv2-xbmc/turtle/"
	elementFormDefault="qualified">


	<xs:annotation>
		<xs:documentation>Turtle is XBMC add-on framework. It has in-built
			utility functions to scrape, find media on video websites like
			YouTube, Dailymotion and more. This Library will be growing
			continuously and can be updated to new version.</xs:documentation>
	</xs:annotation>
	<xs:complexType name="action-type">
		<xs:sequence>
			<xs:element name="move" type="tns:move-type" minOccurs="1"
				maxOccurs="unbounded">
			</xs:element>
			<xs:element name="next-action" type="tns:next-action-type"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
			<xs:element name="redirect-action" type="tns:redirect-action-type" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="pmessage" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>





	<xs:complexType name="move-type">
		<xs:attribute name="module" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="function" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="pmessage" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>






	<xs:element name="turtle" type="tns:turtle-type"></xs:element>

	<xs:complexType name="turtle-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="action" type="tns:action-type">
			</xs:element>
			<xs:element name="include" type="tns:include-type">
			</xs:element>
			<xs:element name="service" type="tns:service-type"></xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="next-action-type">
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="isfolder" type="xs:boolean" use="required"></xs:attribute>
	</xs:complexType>


	<xs:complexType name="include-type">
		<xs:attribute name="file" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="redirect-action-type">
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="service-type">
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="action-id" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== iamfreetofly/iamfreetofly.github.io/script.module.turtle/lib/definition/turtle.xml
<?xml version="1.0" encoding="UTF-8"?>
<turtle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://code.google.com/p/apple-tv2-xbmc/turtle/ turtle.xsd"
	xmlns="https://code.google.com/p/apple-tv2-xbmc/turtle/">

	<service action-id="perform_ping" name="ping" />

	<action id="__start__"
		pmessage="Welcome to TV on DESI ZONE|presented by AJ|based on Turtle">
		<move module="moves.Home" function="displayMenuItems" />
		<next-action name="On_Demand" id="display_TV_Shows"
			isfolder="true" />
		<next-action name="Live" id="display_Live_TV" isfolder="true" />
	</action>

	<!-- Common Video Link Player Moves -->

	<action id="snap_and_play_video">
		<move module="moves.PreProcessor" function="prepareVideoItem" />
		<move module="moves.SnapVideo" function="addPlaylistVideosInfo" />
		<move module="moves.SnapVideo" function="addVideoInfo" />
		<next-action name="Play" id="__play__" isfolder="false" />
	</action>

	<action id="snap_and_directplay_playlist">
		<move module="moves.PreProcessor" function="preparePlayListItems" />
		<move module="moves.SnapVideo" function="addPlaylistVideosInfo" />
		<move module="moves.SnapVideo" function="addVideoInfo" />
		<next-action name="Play" id="__play__" isfolder="false" />
	</action>

</turtle>
